### ISSUE TITLE
1. As a component, I want to be able to read from and write to the Firestore database

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-6-smart-shopping-list#3]
This is 1 of 2 stories that should be finished in the first week in order to enable further development.

AC:

* The following have been added as project dependencies: `firebase` & `react-firestore`
* Make a change in the Firestore database and it shows up in the app
* Make a change in the app and it shows up in the Firestore database

**Comment by segdeha** [comment]
Could satisfy the AC using just a test? Both of y'all are familiar with Jest, so maybe the first commit is to add the project dependencies and make sure Jest is in place?

**Comment by segdeha** [comment]
- 1st pair session Monday at 9am
- Homework: Read up on `firebase` & `react-firestore`
- Add the dependencies and create draft PR

**Comment by skillitzimberg** [comment]
We have connected the app to the database & verified that we can write to it.
- 2nd pair session Tuesday at 9am
- Homework: read up on testing/mocking & `react-firestore`
- Write a test to read from the database
